version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: EPHP
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    #volumes:
      #- ./api/db/db.sql:/docker-entrypoint-initdb.d/db.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - db
  app:
      environment:
        APP_ENV: dev
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - '8000:8000'
      volumes:
      - ./:/app
      depends_on:
        - db
  
